### ISSUE TITLE
Question: Is this officially supported

### ISSUE THREAD

**Issue by alexvdvalk** [bullhorn/extension-configuration-starter#25]
Can you advise if this is an officially support approach to deploying interactions?

I believe page interactions stored on the corporation level. Is this correct? If so, would this lead to duplication when deploying interactions to multiple private labels on the same corporation?

**Comment by johnsully83** [comment]
It is 'officially supported'...this is actually the recommended way to deploy interactions.  The build and upload process lives here
https://github.com/bullhorn/extension-configuration-starter/blob/master/bin/build-and-upload.js
where we do de duplications for exactly the kind of issue you're talking about...we only upload page interactions for the first privateLabel, for field interactions we upload for all.  It's all backed by the Bullhorn CLI (also in GitHub), which in turn is using the BH Extensions REST API.
